version: "3"

services:
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: develop
    ports:
    - "3000:3000"
    depends_on:
      - db-dev
    volumes:
      - ./server:/server
      - /server/node_modules
  db-dev:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=todo-dev
    ports:
    - "5432:5432"
    volumes:
    - ./data/db:/var/lib/postgresql/data

