version: "3.7"

services:
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
    - "3000:3000"
    depends_on:
      - db-dev
    volumes:
      - ./server:/server
      - /server/node_modules
  db-dev:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-dev
    ports:
    - "5432:5432"



